---
- hosts: all
  vars:
    domain_name: "websiteWITHOUTwww.com"
    odoo_install_script_name: "install_odoo_v8.sh"
    odoo_admin_password: "YourODOOPASSWORD"

#Install Syslog-ng
  roles:
  - role: ihrwein.syslog-ng
    syslog_ng_config_version: "3.5"

#Install Postgresql
  - role: zenoamaro.postgresql
    postgresql_listen_addresses:
      - "*"
    postgresql_shared_buffers: 256MB
    postgresql_client_encoding: UTF8
    postgresql_log_destination: syslog
    postgresql_authentication:
      - type: host
        database: 'all'
        user: all
        address: '192.168.1.1/32'
        method: password
      - type: host
        database: 'all'
        user: all
        address: '192.168.1.2/32'
        method: password

#Install Nginx
  - role: jdauphant.nginx
    nginx_official_repo: True
    nginx_worker_processes: auto
    nginx_http_params:
      - sendfile "on"
      - access_log "/var/log/nginx/access.log"
      - error_log "/var/log/nginx/error.log"
      - tcp_nopush on
      - tcp_nodelay on
      - keepalive_timeout 65
      - types_hash_max_size 2048
      - gzip on
      - gzip_disable "msie6"

    nginx_sites:
      odooSite:
        - listen 80
        - server_name www.{{domain_name}}
        - access_log /var/log/nginx/access.log combined
        - error_log /var/log/nginx/error.log
        - keepalive_timeout 60
        - proxy_buffers 16 64k
        - proxy_buffer_size 128k
        - location / { proxy_pass  http://odoo ;
                       proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
                       proxy_redirect off;
                       proxy_set_header Host              $host;
                       proxy_set_header X-Real-IP         $remote_addr;
                       proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                       proxy_set_header X-Forwarded-Proto https;}
        - location ~* /web/static/ { proxy_cache_valid 200 60m;
                                     proxy_buffering on;
                                     expires 864000;
                                     proxy_pass http://odoo;}
        - location /web/database/manager/ { allow 192.168.1.0/24;
                                            deny all;
                                            proxy_pass http://odoo;}
      odooSiteRedirect:
        - listen 80
        - server_name {{domain_name}}
        - return 301 http://www.{{domain_name}}$request_uri
    nginx_configs:
      proxy:
        - proxy_set_header X-Real-IP  $remote_addr
        - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
      upstream:
        - upstream odoo { server 127.0.0.1:8069; }

  tasks:
    - name: Download ODOO Install Script
      get_url: url=https://raw.githubusercontent.com/aschenkels-ictstudio/openerp-install-scripts/master/odoo-v8/ubuntu-14-04/odoo_install.sh dest=/root/{{odoo_install_script_name}}

    - name: Setting ODOO Install Script
      shell: |
          chmod +x ~/{{odoo_install_script_name}}
          perl -pi -e 's/superadminpassword/{{odoo_admin_password}}/g' ~/{{odoo_install_script_name}}

    - name: Install ODOO
      shell: ~/{{odoo_install_script_name}}

    - name: Modify ODOO Admin Password
      shell: perl -pi -e 's/= admin/= {{odoo_admin_password}}/g' /etc/odoo-server.conf

    - name: Remove ODOO Other Addon Path
      shell: perl -pi -e 's/addons_path = \/usr\/lib\/python2.7\/dist-packages\/openerp\/addons//' /etc/odoo-server.conf

    - name: Add Postgresql Log Record To Syslog-ng
      shell: |
          echo '' >> /etc/syslog-ng/syslog-ng.conf
          echo 'destination postgres { file("/var/log/pgsql/pgsql.log"); };' >> /etc/syslog-ng/syslog-ng.conf
          echo 'filter f_postgres { facility(local0); };' >> /etc/syslog-ng/syslog-ng.conf
          echo 'log { source(s_src); filter(f_postgres); destination(postgres); };' >> /etc/syslog-ng/syslog-ng.conf

    - name: Restart Syslog-ng
      shell: service syslog-ng restart
